### ISSUE TITLE
pyATS version 19.9

### ISSUE THREAD

**Issue by urskog84** [CiscoTestAutomation/pyats-docker#3]
Hi Team!

Any chance you will update the container to version 19.9 soon?

**Comment by simingy** [comment]
will do that today

**Comment by urskog84** [comment]
Nic 🥳

**Comment by simingy** [comment]
building...

**Comment by urskog84** [comment]
No module named 'pyats.reporter'  the modue is missing

```
root@9b44c867bc95:/pyats_local# easypy test_job.py -html_logs html_logs/
usage: easypy
Traceback (most recent call last):
  File "src/pyats/utils/import_utils/misc.py", line 52, in pyats.utils.import_utils.misc.import_from_name
  File "/pyats/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 929, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/pyats/easypy/reporter/ae.py", line 11, in init pyats.easypy.reporter.ae
ModuleNotFoundError: No module named 'pyats.reporter'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/pyats/utils/schemaengine.py", line 487, in pyats.utils.schemaengine.Use.validate
  File "src/pyats/utils/import_utils/misc.py", line 55, in pyats.utils.import_utils.misc.import_from_name
ImportError: Failed to import 'pyats.easypy.reporter.ae.AEReporter'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/pyats/utils/yaml/loader.py", line 109, in pyats.utils.yaml.loader.Loader.load
  File "src/pyats/utils/schemaengine.py", line 300, in pyats.utils.schemaengine.Schema.validate
  File "src/pyats/utils/schemaengine.py", line 297, in pyats.utils.schemaengine.Schema.validate
  File "src/pyats/utils/schemaengine.py", line 300, in pyats.utils.schemaengine.Schema.validate
  File "src/pyats/utils/schemaengine.py", line 297, in pyats.utils.schemaengine.Schema.validate
  File "src/pyats/utils/schemaengine.py", line 300, in pyats.utils.schemaengine.Schema.validate
  File "src/pyats/utils/schemaengine.py", line 297, in pyats.utils.schemaengine.Schema.validate
  File "src/pyats/utils/schemaengine.py", line 238, in pyats.utils.schemaengine.Schema.validate
  File "src/pyats/utils/schemaengine.py", line 492, in pyats.utils.schemaengine.Use.validate
pyats.utils.exceptions.SchemaError: import_from_name('pyats.easypy.reporter.ae.AEReporter') raised ImportError("Failed to import 'pyats.easypy.reporter.ae.AEReporter'",)
```
solved after
```
pip install pyats.reporter
```

**Comment by urskog84** [comment]
Have you removed the easypy option -html_logs ??
works in 19.8! 

```
root@9b44c867bc95:/pyats_local/tests# easypy test_job.py -html_logs html_logs/
2019-09-26T21:07:31: %REPORTER-INFO: Starting Reporter Unix socket server------------------
2019-09-26T21:07:31: %REPORTER-INFO: Reporter server (socket /tmp/test_job.2019Sep26_21:07:31.435876.sock) ready to receive requests----------------
2019-09-26T21:07:32: %REPORTER-INFO: Accepted new client connection
2019-09-26T21:07:32: %REPORTER-INFO: Registered Client (pid: 104, num_ctx: 0)
2019-09-26T21:07:32: %EASYPY-INFO: Starting job run: test_job
2019-09-26T21:07:32: %EASYPY-INFO: Runinfo directory: /root/.pyats/runinfo/test_job.2019Sep26_21:07:31.435876
2019-09-26T21:07:32: %EASYPY-INFO: --------------------------------------------------------------------------------
2019-09-26T21:07:35: %REPORTER-INFO: Accepted new client connection
2019-09-26T21:07:35: %REPORTER-INFO: Registered Client (pid: 179, num_ctx: 0)
2019-09-26T21:07:35: %EASYPY-INFO: Starting task execution: Task-1
2019-09-26T21:07:35: %EASYPY-INFO:     test harness = pyats.aetest
2019-09-26T21:07:35: %EASYPY-INFO:     testscript   = /pyats_local/tests/test_main.py
usage: easypy [-datafile FILE] [-uids LOGIC] [-groups LOGIC] [-random]
              [-random_seed INT] [-max_failures INT] [-pdb] [-step_debug FILE]
              [-pause_on PAUSE_ON] [-h] [-loglevel]
easypy: error: argument -h/-help: ignored explicit argument 'tml_logs'
```

**Comment by simingy** [comment]
we did remove --html-logs from the arguments, it was replaced with the new log viewer: `pyats logs view` command.

i see the problem from build, it's going to rebuild in a bit
my apologies

**Comment by simingy** [comment]
this should be fixed now. please pull latest again.

apologies for the issue. let me know if this is resolved

**Comment by urskog84** [comment]
The issue with the pyats.reporter is solved. 

But I'm very disappointed to hear that you remove the `-html_logs` switch from the pyats command.
we currently build a container every night. run our jobfile.py. and extract the html log file to a webserver. where our team can take a lock off the latest test result.

we don't have access to a linux client there we can run the `pyats logs view` command.
so we are using the docker-container to develop en run the test.... :😭

**Comment by simingy** [comment]
hmm
can you run this in a windows WSL? Mac?

Wouldn't it make sense to run a docker container to host these logs?

The new log viewer is quite a bit more powerful, but i'm sure we can find a better way for it to work for you guys

**Comment by urskog84** [comment]
I am, note allowed to run Windows Subsystem for Linux (WSL) in our corporate environment.

Just to make you understand my test setup little better.

Development is done, on windows client together with the docker container.
Jobfile, tests and Dockerfilte is den pushed to our internal git/bitbucket.

every night a schedule AWX/Ansibel job is run on a"docker host". it
- pulls the master branch
- builds a docker container
- start the container with a local volume
- the test is run against 130 devices. the tests take about 45 minutes to finish.
- the html logs is then picked up from docker host local drive and is shipped to a web-server.
- my team can then look att the html report, and take action..

I open for suggestions to improve my test pipeline. pleas help me out.

regards Petter Fors

**Comment by simingy** [comment]
Hi

Ok, Monday first thing we'll look into unblocking you. Would you mind sending us an email at pyats-support-ext@cisco.com and we can book a webex meeting to discuss various options?

We'd like you to enjoy the new log viewer, but of course have it work in your env.

**Comment by simingy** [comment]
update, the team is looking into adding back html logs.

I'd still like to discuss an option to remove it and have you use the new log viewer. Thoughts?

**Comment by urskog84** [comment]
Hello! I look forward to have a discussen with you, and the team. I tok the time to play round with the pyats logs view command in my home lab.

I can see the benefits...

**Comment by bastell** [comment]
Hi,
The --html-logs argument has been re-added to pyATS.
To get this patch, run:
`pip install --upgrade pyats.easypy`
`pip install --upgrade pyats.reporter`
