### ISSUE TITLE
Recieving "ReportServer could not start after 30 seconds" error after running a test job

### ISSUE THREAD

**Issue by SudarshanVK** [CiscoTestAutomation/pyats-docker#6]
Pyats docker version 
---------------------------------------------------------------------------------------
`(pyats) root@bca36fee1ec0:~# pyats version check
You are currently running pyATS version: 20.10
Python: 3.6.10 [64bit]

  Package                      Version
  ---------------------------- -------
  genie                        20.10
  genie.libs.clean             20.10
  genie.libs.conf              20.10
  genie.libs.filetransferutils 20.10
  genie.libs.health            20.10
  genie.libs.ops               20.10
  genie.libs.parser            20.10
  genie.libs.robot             20.10
  genie.libs.sdk               20.10
  genie.telemetry              20.10
  genie.trafficgen             20.10
  pyats                        20.10
  pyats.aereport               20.10
  pyats.aetest                 20.10
  pyats.async                  20.10
  pyats.connections            20.10
  pyats.contrib                20.10.3
  pyats.datastructures         20.10
  pyats.easypy                 20.10
  pyats.kleenex                20.10
  pyats.log                    20.10
  pyats.reporter               20.10
  pyats.results                20.10
  pyats.robot                  20.10
  pyats.tcl                    20.10
  pyats.topology               20.10
  pyats.utils                  20.10
  unicon                       20.10
  unicon.plugins               20.10

(pyats) root@bca36fee1ec0:~#`

Full traceback of the error 

`(pyats) root@bca36fee1ec0:~# pyats run job test_cases/test_connection_job.py --testbed svk_testbed.yaml
2020-11-26T05:38:34: %REPORTER-WARNING: Attempting to start ReportServer... (5s/30s)
2020-11-26T05:38:39: %REPORTER-WARNING: Attempting to start ReportServer... (10s/30s)
2020-11-26T05:38:44: %REPORTER-WARNING: Attempting to start ReportServer... (15s/30s)
2020-11-26T05:38:49: %REPORTER-WARNING: Attempting to start ReportServer... (20s/30s)
2020-11-26T05:38:54: %REPORTER-WARNING: Attempting to start ReportServer... (25s/30s)
2020-11-26T05:38:59: %REPORTER-ERROR: ReportServer could not start after 30 seconds
2020-11-26T05:38:59: %EASYPY-ERROR: !!! an unhandled exception has interrupted execution !!!
2020-11-26T05:38:59: %EASYPY-ERROR:
2020-11-26T05:38:59: %EASYPY-ERROR: This may be caused by:
2020-11-26T05:38:59: %EASYPY-ERROR:     - keyboard interrupts (ctrl+c)
2020-11-26T05:38:59: %EASYPY-ERROR:     - job file issues
2020-11-26T05:38:59: %EASYPY-ERROR:     - unexpected exceptions from your plugins
2020-11-26T05:38:59: %EASYPY-ERROR:
2020-11-26T05:38:59: %EASYPY-ERROR: As a consequence:
2020-11-26T05:38:59: %EASYPY-ERROR:     - execution crashed and the environment may not be cleaned up
2020-11-26T05:38:59: %EASYPY-ERROR:     - TRADE/TIMS uploading will likely not occur
2020-11-26T05:38:59: %EASYPY-ERROR:
2020-11-26T05:38:59: %EASYPY-ERROR: Please investigate the traceback below before raising issue to pyats-support.
2020-11-26T05:38:59: %EASYPY-ERROR:
2020-11-26T05:38:59: %EASYPY-ERROR: --------------------------------------------------------------------------------
2020-11-26T05:38:59: %EASYPY-ERROR:
2020-11-26T05:38:59: %EASYPY-ERROR: pyATS Instance   : /pyats
2020-11-26T05:38:59: %EASYPY-ERROR: Python Version   : cpython-3.6.10 (64bit)
2020-11-26T05:38:59: %EASYPY-ERROR: CLI Arguments    : /pyats/bin/pyats run job test_cases/test_connection_job.py --testbed svk_testbed.yaml
2020-11-26T05:38:59: %EASYPY-ERROR: User             : root
2020-11-26T05:38:59: %EASYPY-ERROR: Host Server      : bca36fee1ec0
2020-11-26T05:38:59: %EASYPY-ERROR: Host OS Version  : Debian GNU/Linux 10 buster (x86_64)
2020-11-26T05:38:59: %EASYPY-ERROR:
2020-11-26T05:38:59: %EASYPY-ERROR: Traceback (most recent call last):
2020-11-26T05:38:59: %EASYPY-ERROR:   File "src/pyats/easypy/reporter/ae.py", line 79, in pyats.easypy.reporter.ae.AEReporter.start
2020-11-26T05:38:59: %EASYPY-ERROR:   File "src/pyats/reporter/server.py", line 876, in pyats.reporter.server.ReportServer.start_server
2020-11-26T05:38:59: %EASYPY-ERROR: pyats.reporter.exceptions.ServerNotStartedError: ReportServer could not start after 30 seconds
2020-11-26T05:38:59: %EASYPY-INFO: Sending report email...
2020-11-26T05:38:59: %EASYPY-INFO: Missing SMTP server configuration, or failed to reach/authenticate/send mail. Result notification email failed to send.
2020-11-26T05:38:59: %EASYPY-INFO: Creating archive file: /root/.pyats/archive/20-Nov/test_connection_job.2020Nov26_05:38:30.866360.zip
Process ForkProcess-2:
Traceback (most recent call last):
  File "src/pyats/reporter/server.py", line 914, in pyats.reporter.server.ReportServer._run_server
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "src/pyats/reporter/server.py", line 929, in pyats.reporter.server.ReportServer._run_server
  File "src/pyats/reporter/server.py", line 56, in pyats.reporter.server.signal_catcher
pyats.reporter.exceptions.SignalError: Received SIGTERM
2020-11-26T05:38:59: %EASYPY-INFO: Done!`

**Comment by SudarshanVK** [comment]
Hey Guys, any help with this?

**Comment by bastell** [comment]
Hi,
Is this the ciscotestautomation/pyats image or an image using it as a base? Can you also please check the reporter.log file in the generated archive at `/root/.pyats/archive/20-Nov/test_connection_job.2020Nov26_05:38:30.866360.zip`? It contains additional information about the running of the reporter server which may help diagnose what went wrong.
