### ISSUE TITLE
How to fix this _tkinter.TclError: can't find package Tclx

### ISSUE THREAD

**Issue by kotini** [CiscoTestAutomation/pyats-docker#9]
I am running docker container with mounting 
**docker run -it -v /auto/pysw/ats64/:/auto/pysw/ats64/  -v $PWD:/pyats/unified-perf ciscotestautomation/pyats:latest bash**

I am doing 
**source  /pyats/bin/activate**
**source /auto/pysw/ats64/env.sh**
Then running easypy command getting below error '

2021-06-22T10:23:31: %EASYPY-INFO: Job finished. Wrapping up...
2021-06-22T10:23:31: %EASYPY-ERROR: Caught 1 or more error in Easypy plugins:
2021-06-22T10:23:31: %EASYPY-ERROR: TestbedPlugin[pre_job] Traceback (most recent call last):
2021-06-22T10:23:31: %EASYPY-ERROR:   File "src/pyats/utils/schemaengine.py", line 603, in pyats.utils.schemaengine.Use.validate
2021-06-22T10:23:31: %EASYPY-ERROR:   File "src/pyats/utils/import_utils/misc.py", line 44, in pyats.utils.import_utils.misc.import_from_name
2021-06-22T10:23:31: %EASYPY-ERROR:   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
2021-06-22T10:23:31: %EASYPY-ERROR:     return _bootstrap._gcd_import(name[level:], package, level)
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-06-22T10:23:31: %EASYPY-ERROR:   File "/pyats/lib/python3.6/site-packages/hltapi/__init__.py", line 3, in <module>
2021-06-22T10:23:31: %EASYPY-ERROR:     from .legacy import Ixia, Spirent, Pagent
2021-06-22T10:23:31: %EASYPY-ERROR:   File "/pyats/lib/python3.6/site-packages/hltapi/legacy.py", line 5, in <module>
2021-06-22T10:23:31: %EASYPY-ERROR:     from ats.tcl import Interpreter, KeyedList
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
2021-06-22T10:23:31: %EASYPY-ERROR:   File "<frozen importlib._bootstrap>", line 571, in module_from_spec
2021-06-22T10:23:31: %EASYPY-ERROR:   File "src/pyats/utils/import_utils/legacy.py", line 33, in pyats.utils.import_utils.legacy.LegacyLoader.create_module
2021-06-22T10:23:31: %EASYPY-ERROR:   File "/pyats/lib/python3.6/site-packages/pyats/tcl/__init__.py", line 38, in <module>
2021-06-22T10:23:31: %EASYPY-ERROR:     from .interpreter import Interpreter, _global_interpreter
2021-06-22T10:23:31: %EASYPY-ERROR:   File "src/pyats/tcl/interpreter.py", line 756, in init pyats.tcl.interpreter
2021-06-22T10:23:31: %EASYPY-ERROR:   File "src/pyats/tcl/interpreter.py", line 90, in pyats.tcl.interpreter.Interpreter.__init__
2021-06-22T10:23:31: %EASYPY-ERROR: _tkinter.TclError: can't find package Tclx
2021-06-22T10:23:31: %EASYPY-ERROR:

**Comment by ThomasJRyan** [comment]
It looks like you're trying to use TCL in your Docker container. We no longer support TCL. I would recommend either trying to not use it, but if it's a requirement you will need to reach out to TCL groups
